language: cpp
compiler:
  - g++
  - clang++
install:
  - sudo apt-get install libsfml-dev=2.1
notifications:
  recipients:
    - jordan@nodetwo.net
  email:
    on_success: change
    on_failure: always
