language: cpp
compiler:
  - gcc
  - clang
install:
  - sudo apt-get install libsfml-dev=2.0
notificaions:
  recipients:
    - jordan@nodetwo.net
  email:
    on_success: change
    on_failure: always
