language: cpp
compiler:
  - g++
  - clang++
before_script:
  - sudo add-apt-repository ppa:sonkun/sfml-stable
  - sudo apt-get update -q
install:
  - sudo apt-get install libsfml-dev=2.0
notifications:
  recipients:
    - jordan@nodetwo.net
  email:
    on_success: change
    on_failure: always